spring.datasource.username=root
spring.datasource.password=Jamesbond123
spring.datasource.url=jdbc:mysql://localhost:3306/encuestadb
spring.jpa.hibernate.ddl-auto=update
tokenSecret=safdklj52345jkasd0821345ljkadsf0891234lj